# Generated by Django 5.2 on 2025-05-06 20:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('piky', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pApe', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('mApe', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('bDay', models.DateField()),
                ('asunto', models.CharField(max_length=100)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MX')),
                ('curp', models.CharField(max_length=18)),
                ('sexo', models.CharField(max_length=10)),
                ('dirr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='soli',
            fields=[
                ('piky', models.AutoField(primary_key=True, serialize=False)),
                ('dirr', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data')),
            ],
        ),
    ]
