# Generated by Django 5.2 on 2025-07-21 10:58

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('data_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('pApe', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('mApe', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('bDay', models.DateField()),
                ('asunto', models.CharField(max_length=30)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MX')),
                ('curp', models.CharField(max_length=18)),
                ('sexo', models.CharField(max_length=10)),
                ('dirr', models.TextField()),
                ('disc', models.CharField(max_length=100, verbose_name='discapacidad')),
                ('etnia', models.CharField(max_length=100, verbose_name='etnia')),
                ('vul', models.CharField(max_length=100, verbose_name='vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Datos',
                'db_table': 'dataT',
                'ordering': ['data_ID'],
                'get_latest_by': 'data_ID',
            },
        ),
        migrations.CreateModel(
            name='SubirDocs',
            fields=[
                ('doc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nomDoc', models.CharField(blank=True, max_length=50, null=True)),
                ('descDoc', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='documents/')),
                ('fechaDoc', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Documentos',
                'db_table': 'files',
                'ordering': ['fechaDoc'],
            },
        ),
        migrations.CreateModel(
            name='Uuid',
            fields=[
                ('prime', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('pfm', models.CharField(blank=True, max_length=80, null=True)),
                ('data_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='datos')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['pago_ID'],
            },
        ),
        migrations.CreateModel(
            name='soli',
            fields=[
                ('soli_ID', models.AutoField(primary_key=True, serialize=False)),
                ('dirr', models.TextField()),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('cp', models.CharField(blank=True, max_length=5, null=True)),
                ('descc', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('puo', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('data_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='Datos')),
                ('doc_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desUr.subirdocs', verbose_name='Documentos')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'db_table': 'soli',
                'ordering': ['data_ID'],
            },
        ),
        migrations.AddField(
            model_name='subirdocs',
            name='fuuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.uuid'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fDoc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('finalDoc', models.FileField(upload_to='solicitudes/')),
                ('nomDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('soli_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.soli')),
                ('fuuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.uuid')),
            ],
            options={
                'verbose_name': 'solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['fDoc_ID'],
            },
        ),
        migrations.AddField(
            model_name='data',
            name='fuuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.uuid', verbose_name='ides'),
        ),
    ]
