# Generated by Django 5.2 on 2025-05-09 18:11

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('data_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('pApe', models.CharField(max_length=30, verbose_name='Apellido Paterno')),
                ('mApe', models.CharField(max_length=30, verbose_name='Apellido Materno')),
                ('bDay', models.DateField()),
                ('asunto', models.CharField(max_length=30)),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MX')),
                ('curp', models.CharField(max_length=18)),
                ('sexo', models.CharField(max_length=10)),
                ('dirr', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Datos',
                'db_table': 'dataT',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubirDocs',
            fields=[
                ('doc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nomDoc', models.CharField(max_length=50)),
                ('descDoc', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='documents/')),
                ('fechaDoc', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Documentos',
                'db_table': 'files',
                'ordering': ['fechaDoc'],
            },
        ),
        migrations.CreateModel(
            name='soli',
            fields=[
                ('soli_ID', models.AutoField(primary_key=True, serialize=False)),
                ('dirr', models.CharField(max_length=50)),
                ('descc', models.TextField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('data_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='Datos')),
                ('doc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.subirdocs', verbose_name='Documentos')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'db_table': 'soli',
                'ordering': ['data_ID'],
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=30)),
                ('data_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='Datos')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'db_table': 'users',
                'ordering': ['user_ID'],
            },
        ),
    ]
