# Generated by Django 5.2 on 2025-05-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soli',
            name='data_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='Datos'),
        ),
        migrations.AlterField(
            model_name='soli',
            name='doc_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='desUr.subirdocs', verbose_name='Documentos'),
        ),
    ]
