# Generated by Django 5.0 on 2025-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soli',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soli',
            name='colonia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
