# Generated by Django 5.2 on 2025-05-23 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('pfm', models.CharField(blank=True, max_length=80, null=True)),
                ('data_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='datos')),
            ],
            options={
                'db_table': 'pagos',
                'ordering': ['pago_ID'],
            },
        ),
    ]
