# Generated by Django 5.2 on 2025-05-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soli',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fDoc_ID', models.AutoField(primary_key=True, serialize=False)),
                ('finalDoc', models.FileField(upload_to='solicitudes')),
                ('nomDoc', models.CharField(blank=True, max_length=255, null=True)),
                ('fuuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.uuid')),
            ],
            options={
                'verbose_name': 'solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['fDoc_ID'],
            },
        ),
    ]
