# Generated by Django 5.2 on 2025-06-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='soli_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desUr.soli'),
        ),
    ]
