# Generated by Django 5.2 on 2025-05-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0002_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='soli',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='soli',
            name='puo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
