# Generated by Django 5.2 on 2025-05-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0002_alter_soli_data_id_alter_soli_doc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='Datos'),
        ),
    ]
