# Generated by Django 5.2 on 2025-05-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0003_alter_users_data_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soli',
            name='doc_ID',
        ),
    ]
