# Generated by Django 5.2 on 2025-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0003_soli_foto_soli_puo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soli',
            name='foto',
            field=models.ImageField(blank=True, default='desUr/static/fotos/mock.jpg', null=True, upload_to='fotos'),
        ),
    ]
