# Generated by Django 5.2 on 2025-05-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0004_remove_soli_doc_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'get_latest_by': 'data_ID', 'ordering': ['data_ID'], 'verbose_name': 'Datos'},
        ),
        migrations.AlterField(
            model_name='soli',
            name='data_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.data', verbose_name='Datos'),
        ),
        migrations.AlterField(
            model_name='subirdocs',
            name='nomDoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
