# Generated by Django 5.2 on 2025-07-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0004_ppgeneral_ppescuela_ppcs_ppinfraestructura_ppparque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppgeneral',
            name='agua',
        ),
        migrations.RemoveField(
            model_name='ppgeneral',
            name='alumbrado',
        ),
        migrations.RemoveField(
            model_name='ppgeneral',
            name='cfe',
        ),
        migrations.RemoveField(
            model_name='ppgeneral',
            name='climas',
        ),
        migrations.RemoveField(
            model_name='ppgeneral',
            name='drenaje',
        ),
        migrations.RemoveField(
            model_name='ppgeneral',
            name='impermabilizacion',
        ),
        migrations.AddField(
            model_name='ppgeneral',
            name='instalation_choices',
            field=models.JSONField(blank=True, default=dict, help_text='Seleccione las instalaciones necesarias para la propuesta.', null=True, verbose_name='isntalaciones'),
        ),
    ]
