# Generated by Django 5.2 on 2025-05-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0005_alter_data_options_alter_soli_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soli',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
