# Generated by Django 5.2 on 2025-05-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0006_soli_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='soli',
            name='doc_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desUr.subirdocs', verbose_name='Documentos'),
        ),
    ]
