# Generated by Django 5.2 on 2025-05-13 14:27
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0007_soli_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='docsSubidos',
            fields=[
                ('up_ID', models.AutoField(primary_key=True, serialize=False)),
                ('doc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.subirDocs', verbose_name='Documentos')),
                ('numDocs', models.PositiveIntegerField(blank=True, null=True))
            ],
        ),
    ]
