# Generated by Django 5.2 on 2025-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0008_soli_nada'),
    ]

    operations = [
        migrations.AddField(
            model_name='subirdocs',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='docsSubidos',
        ),
    ]
