# Generated by Django 5.2 on 2025-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0009_subirdocs_count_delete_docssubidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('count_ID', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contador',
                'ordering': ['count'],
            },
        ),
        migrations.RemoveField(
            model_name='subirdocs',
            name='count',
        ),
    ]
