# Generated by Django 5.2 on 2025-05-13 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0010_contador_remove_subirdocs_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
