# Generated by Django 5.2 on 2025-05-14 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0010_contador_remove_subirdocs_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='uuid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='desUr.uuid', verbose_name='ides'),
            preserve_default=False,
        ),
    ]
