# Generated by Django 5.2 on 2025-05-14 20:50

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Uuid = apps.get_model("desUr", "Uuid")
    for row in Uuid.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])



class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0011_uuid_data_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),    ]
