# Generated by Django 5.2 on 2025-05-13 20:24

import uuid
from django.db import migrations, models



def gen_uuid(apps, schema_editor):
    data = apps.get_model("desUr", "data")
    for row in data.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0010_contador_remove_subirdocs_count'),
    ]

    operations = [
        migrations.RunPython(gen_uuid,
        reverse_code=migrations.RunPython.noop),
    ]
