# Generated by Django 5.2 on 2025-05-14 20:50
import uuid

from django.db import migrations

from portaldu.desUr import models


class Migration(migrations.Migration):

    dependencies = [
        ('desUr', '0012_auto_20250514_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name="Uuid",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
