# Generated by Django 5.2 on 2025-06-03 20:45

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('desUr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('bday', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'cmin_users',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='LoginDate',
            fields=[
                ('login_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuarios')),
            ],
            options={
                'db_table': 'LoginDate',
                'ordering': ['user_FK'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudesPendientes',
            fields=[
                ('solicitud_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nomSolicitud', models.CharField(max_length=150)),
                ('fechaSolicitud', models.DateField()),
                ('doc_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.files', verbose_name='documentos')),
            ],
            options={
                'db_table': 'SolicitudesPendientes',
                'ordering': ['solicitud_ID'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudesEnviadas',
            fields=[
                ('solicitud_ID', models.AutoField(primary_key=True, serialize=False)),
                ('nomSolicitud', models.CharField(max_length=150)),
                ('fechaEnvio', models.DateField(auto_now=True)),
                ('doc_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desUr.files', verbose_name='documentos')),
                ('user_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuarios')),
                ('solicitud_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmin.solicitudespendientes', verbose_name='solicitudes')),
            ],
            options={
                'db_table': 'SolicitudesEnviadas',
                'ordering': ['solicitud_ID'],
            },
        ),
    ]
